<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>tea_teleop</name>
    <version>0.0.1</version>
    <description>Tea-Picking-Dual-Arm 主从遥操作程序</description>
    <maintainer email="kaerei86@gmail.com">kaede-rei</maintainer>
    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>ament_index_cpp</depend>
    <depend>yaml-cpp</depend>
    <depend>serial_arm_core</depend>
    <depend>serial_arm_hardware_hiwonder</depend>
    <depend>tea_leader_description</depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
